/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
   
   ANSWER ON NOTE: Shut up
*/

#import "AppDelegate.h"

#import <appkit/appkit.h>

id appDelegate;

void main(int argc, char *argv[]) {

	[Application new];
	
	appDelegate = [[AppDelegate alloc] init];
	[NXApp setDelegate:appDelegate];

	[NXApp run];

	[NXApp free];
	[appDelegate free];
	
	exit(0);
}